[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  publish = "public"
  functions = "netlify/functions"
  framework = "#static"


[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200  